sudo: required
services:
  - docker

before_install:
  - docker build -t bhadash1/react-test -f ./client/Dev.Dockerfile ./client

script:
  - docker run -e CI=true bhadash1/react-test npm run test

after_success:
  - docker build -t bhadash1/client ./client
  - docker build -t bhadash1/api ./api
  - docker build -t bhadash1/mongo ./mongo
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push to docker hub
  - docker push bhadash1/client
  - docker push bhadash1/api
  - docker push bhadash1/mongo

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: rick-and-morty
  env: RickAndMorty-env
  bucket_name: elasticbeanstalk-us-east-2-089781076407
  bucket_path: docker-rick-and-morty
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
