version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dev.Dockerfile
      context: ./nginx
    ports:
      - '3050:80'

  mongo:
    build: ./mongo/.
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rickmorty
    ports:
      - 27017:27017
    image: rickmorty/mongo

  api:
    build: ./api/.
    restart: always
    depends_on:
        - mongo
    ports:
      - "5000:5000"
    image: rickmorty/api

  client:
    build:
      context: ./client/.
    restart: always
    ports:
      - "3000:3000"
    image: rickmorty/web