version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dev.Dockerfile
      context: ./nginx
    ports:
      - '3050:80'

  mongodb_container:
    build: ./mongo/.
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rickmorty
    ports:
      - 27017:27017
    image: rickmorty/mongo

  api_container:
    build: ./api/.
    restart: always
    depends_on:
        - mongodb_container
    ports:
      - "3001:3001"
    image: rickmorty/api

  node_container:
    build:
      context: ./client/.
    restart: always
    depends_on:
        - api_container
    ports:
      - "8080:8080"
    image: rickmorty/web